### PR TITLE
fix TypeError: options is undefined #55

### PR DESCRIPTION
**Pull request by Densyakun**

### CODE REVIEW

**Comment by ogroppo** [comment]
Hey! Thank you very much for the fix - Closes https://github.com/codeledge/ra-data-simple-prisma/pull/56

**Comment by ogroppo** [comment]
published `ra-data-simple-prisma@2.1.1`

**Comment by Densyakun** [comment]
An error occurred when importing and using this module installed from npm because the file dist/index.mjs has not been updated to v2.1.1.

**Comment by ogroppo** [comment]
Yeah you're right sorry, the module was not building on publish - please check `ra-data-simple-prisma@2.1.2` and let me know 👍

**Comment by Densyakun** [comment]
I have checked that it has been fixed. Thank you very much.

**Pull request merged**
