### PR TITLE
Support json update

### PR DESCRIPTION
**Pull request by heba-khazbak**
if the field type is json, it is always filtered out and not updated.
so I added this option
or is there another way to update a json field?

### CODE REVIEW

**Review by ogroppo — COMMENTED** [review]
Hi! yeah I think this is a valid solution, could you also bump the package version so I will publish?

**Review by ogroppo — COMMENTED** [review]
Ah sorry, I noticed you added the package-json file, however this is a pnpm monorepo, could you remove the file please

**Comment by heba-khazbak** [comment]
@ogroppo yes sure, done

**Comment by ogroppo** [comment]
published `+ ra-data-simple-prisma@1.0.3` 🥳

**Comment by heba-khazbak** [comment]
Thank you 🥳 :tada:

**Pull request merged**
